import type { Metadata } from "next";
import "./globals.css";

import { Quantico } from "next/font/google";

const quantico = Quantico({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quantico.className} antialiased`}>{children}</body>
    </html>
  );
}
